config/routes.rb
MusicApp::Application.routes.draw do
  root to: "sessions#new"
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  shallow do
    resources :bands do
      resources :albums do
        resources :tracks do
          resources :notes
        end
      end
    end
  end
  
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  name       :string(255)      not null
#  year       :integer          not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime
#  updated_at :datetime
#

class Album < ActiveRecord::Base
	belongs_to :band
	has_many :tracks

	validates :band, :name, :year, presence:true
	validates :live, inclusion: {in: [true, false]}
	validates :name, uniqueness: {scope: :band_id}
	validates :year, numericality: {minimum: 1900, maximum: 3000}
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Band < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true

	has_many :albums, dependent: :destroy
	has_many :tracks, through: :albums, source: :tracks
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
	belongs_to :track

	validates :user, :track, presence: true
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  name       :string(255)      not null
#  lyrics     :text             not null
#  ord        :integer          not null
#  bonus      :boolean          default(FALSE), not null
#  created_at :datetime
#  updated_at :datetime
#

class Track < ActiveRecord::Base
	belongs_to :album
	has_one :band, through: :album, source: :band
	has_many :notes

	validates :album, :name, :lyrics, :ord, presence: true
	validates :bonus, inclusion: {in: [true, false]}
	validates :ord, uniqueness: {scope: :album_id}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
	attr_reader :password
	before_validation :ensure_session_token
	validates :email, :password_digest, :session_token, presence: true
	validates :email, :session_token, uniqueness: true
	validates :password, length: {minimum: 6, allow_nil: true}

	has_many :notes

	def self.find_by_credentials(email, password)
		user = User.find_by_email(email)
		return nil if user.nil?
		user.is_password?(password) ? user : nil
	end

	def reset_session_token!
		self.session_token = SecureRandom.hex
		self.save!
		self.session_token
	end

	def password=(password)
		if password.present?
			@password = password
			self.password_digest = BCrypt::Password.create(password)
		end
	end

	def is_password?(password)
		BCrypt::Password.new(self.password_digest).is_password?(password)
	end

	def ensure_session_token
		self.session_token ||= SecureRandom.hex
	end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	before_action :require_signed_in
	
	def index
		@albums = Album.all
		render :index
	end

	def show
		@album = Album.find(params[:id])
		render :show
	end

	def new
		@album = Album.new(band_id: params[:band_id])
		render :new
	end

	def create
		@album = Album.new(album_params)

    	if @album.save
    		redirect_to album_url(@album)
    	else
    		flash.now[:errors] = @album.errors.full_messages
      		render :new
    	end
	end

	def edit
		@album = Album.find(params[:id])
		render :edit
	end

	def update
    	@album = Album.find(params[:id])

	    if @album.update_attributes(album_params)
	    	redirect_to album_url(@album)
	    else
	    	flash.now[:errors] = @album.errors.full_messages
	    	render :edit
	    end
	end

	def destroy
		@album = Album.find(params[:id])
    	@album.destroy
	end

	private

	def album_params
		params.require(:album).permit(:band_id, :live, :name, :year)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?, :require_signed_in

  private

  def current_user
  	return nil unless session[:token]
  	@current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
  	!!current_user
  end

  def sign_in(user)
  	session[:token] = user.reset_session_token!
  end

  def sign_out
  	current_user.try(:reset_session_token!)
  	session[:token] = nil
  end

  def require_signed_in
  	redirect_to new_session_url unless signed_in?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
	before_action :require_signed_in
	
	def index
		@bands = Band.all
		render :index
	end

	def show
		@band = Band.find(params[:id])
		render :show
	end

	def new
		@band = Band.new
		render :new
	end

	def create
		@band = Band.new(band_params)

		if @band.save
			redirect_to band_url(@band)
		else
			flash.now[:errors] = @band.errors.full_messages
			render :new
		end
	end

	def edit
		@band = Band.find(params[:id])
		render :edit
	end

	def update
		@band = Band.find(params[:id])

		if @band.update_attributes(band_params)
			redirect_to band_url(@band)
		else
			flash.now[:errors] = @band.errors.full_messages
			render :edit
		end
	end

	def destroy
		@band = Band.find(params[:id])
		@band.destroy
	end

	private

	def band_params
		params.require(:band).permit(:name)
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :require_signed_in

	def create
		@note = Note.new(note_params)
		@track = Track.find(params[:track_id])

		if @note.save
			redirect_to track_url(@track)
		else
			flash.now[:errors] = @note.errors.full_messages
		end
	end

	def destroy
		@note = Note.find(params[:id])
		@track = Track.find(@note.track_id)
		@note.destroy
		redirect_to track_url(@track)
	end

	private

	def note_params
		params.require(:note).permit(:user_id, :track_id, :body)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		render :new
	end

	def create
		@user = User.find_by_credentials(
			params[:user][:email],
			params[:user][:password])

		if @user
			sign_in(@user)
			redirect_to bands_url
		else
			flash.now[:errors] = ["Invalid username or password."]
			render :new
		end
	end

	def destroy
		sign_out
		redirect_to new_session_url
	end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_signed_in
  
  def index
    @tracks = Track.all
    render :index
  end

  def show
    @track = Track.find(params[:id])
    @user = current_user
    render :show
  end

  def new
    @track = Track.new(album_id: params[:album_id])
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
    	flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])

    if @track.update_attributes(track_params)
    	redirect_to track_url(@track)
    else
    	flash.now[:errors] = @track.errors.full_messages
    	render :edit
    end

  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
  end

  private

  def track_params
    params.require(:track).permit(:album_id, :bonus, :lyrics, :name, :ord)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
		render :new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			sign_in(@user)
			redirect_to bands_url
		else
			flash.now[:errors] = @user.errors.full_messages
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
		render :show
	end

	private

	def user_params
		params.require(:user).permit(:email, :password)
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<form action="<%= album_url %>" method="POST">
	<input type="hidden" name="_method" value="PATCH">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

	<label>Album Name: 
		<input type="text" name="album[name]" value="<%= @album.name%>"></label><br>

	<label>Band Name: 
		<select name="album[band_id]" value="<%= @album.band_id %>">
			<%= Band.all.each do |band| %>
				<option <%= @album.band_id == band.id ? 'selected' : '' %> value="<%= band.id%>">
					<%= band.name %>
				</option>
			<% end %>
		</select>
	</label><br>

	<label>Album Year: 
		<input type="text" name="album[year]" value="<%= @album.year %>"></label><br>

	<label>Live Recording?
		<select name="album[live]" value="<%= @album.live %>">
			<option <%= @album.live ? 'selected' : '' %> value="true">Live</option>
			<option <%= @album.live ? '' : 'selected' %> value="false">Studio</option>
		</select>
	</label><br>

	<input type="submit" value="Edit Album">
</form>

app/views/albums/index.html.erb
<h1>All Albums</h1>

<ul>
	<% @albums.each do |album| %>
		<li><%= link_to album.name, album_url(album) %></li>
	<% end %>
</ul>

app/views/albums/new.html.erb
<h1>Create a New Album</h1>

<form action="<%= band_albums_url %>" method="POST">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

	<label>Album Name: 
		<input type="text" name="album[name]"></label><br>

	<label>Band Name: 
		<select name="album[band_id]">
			<%= Band.all.each do |band| %>
				<option <%= @album.band_id == band.id ? 'selected' : '' %> value="<%= band.id%>">
					<%= band.name %>
				</option>
			<% end %>
		</select>
	</label><br>

	<label>Album Year: 
		<input type="text" name="album[year]"></label><br>

	<label>Live Recording?
		<select name="album[live]">
			<option <%= @album.live ? 'selected' : '' %> value="true">Live</option>
			<option <%= @album.live ? '' : 'selected' %> value="false">Studio</option>
		</select>
	</label><br>

	<input type="submit" value="Create an Album">
</form>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>

<ul>
	<li><%= @album.year %></li>
	<li><%= @album.live ? 'Live Recording' : 'Studio Recording' %></li>
</ul>

<h3>Band</h3>
<ul>
	<li><%= link_to @album.band.name, band_url(@album.band) %></li>
</ul>

<h3>Tracks</h3>
<ul>
	<% @album.tracks.each do |track| %>
		<li><%= link_to track.name, track_url(track) %></li>
	<% end %>
</ul>

app/views/bands/edit.html.erb
<h1>Edit a Band</h1>

<form action="<%= band_url(@band) %>" method="POST">
	<input type="hidden" name="_method" value="PATCH">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

	<label>Band Name: 
		<input type="text" name="band[name]" value="<%= @band.name %>"></label>

	<input type="submit" value="Create a Band">
</form>

app/views/bands/index.html.erb
<h1>All Bands</h1>

<ul>
	<% @bands.each do |band| %>
		<li><%= link_to band.name, band_url(band) %></li>
	<% end %>
</ul>

app/views/bands/new.html.erb
<h1>Create a New Band</h1>

<form action="<%= bands_url %>" method="POST">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

	<label>Band Name: 
		<input type="text" name="band[name]"></label>

	<input type="submit" value="Create a Band">
</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<h3>Albums</h3>
<ul>
	<% @band.albums.each do |album| %>
		<li><%= link_to album.name, album_url(album)%></li>
	<% end %>
</ul>

<h3>Tracks</h3>
<ul>
	<% @band.tracks.each do |track| %>
		<li><%= link_to track.name, track_url(track) %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tracks/edit.html.erb
<h1>Edit a Track</h1>

<form action="<%= track_url(@track) %>" method="POST">
	<input type="hidden" name="_method" value="PATCH">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

	<label>Track Name: 
		<input type="text" name="track[name]" value="<%= @track.name %>"></label><br>

	<label>Album Name: 
		<select name="track[album_id]" value="<%= @track.album_id %>">
			<%= Album.all.each do |album| %>
				<option <%= @track.album_id == album.id ? 'selected' : '' %> value="<%= album.id%>">
					<%= album.name %>
				</option>
			<% end %>
		</select>
	</label><br>

	<label>Lyrics
		<input type="textarea" name="track[lyrics]" value="<%= @track.lyrics %>"></label><br>

	<label>Track Order
		<input type="text" name="track[ord]" value="<%= @track.ord %>"></label><br>

	<label>Bonus Track?
		<select name="track[bonus]" value="<%= @track.bonus %>">
			<option value="true">Bonus</option>
			<option value="false">Regular</option>
		</select>
	<label><br>

	<input type="submit" value="Create a Track">
</form>

app/views/tracks/index.html.erb
<h1>All Tracks</h1>

<ul>
	<% @tracks.each do |track| %>
		<li><%= link_to track.name, track_url(track) %></li>
	<% end %>
</ul>

app/views/tracks/new.html.erb
<h1>Create a New Track</h1>

<form action="<%= album_tracks_url %>" method="POST">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

	<label>Track Name: 
		<input type="text" name="track[name]"></label><br>

	<label>Album Name: 
		<select name="track[album_id]">
			<%= Album.all.each do |album| %>
				<option <%= @track.album_id == album.id ? 'selected' : '' %> value="<%= album.id%>">
					<%= album.name %>
				</option>
			<% end %>
		</select>
	</label><br>

	<label>Lyrics
		<input type="text" name="track[lyrics]"></label><br>

	<label>Track Order
		<input type="text" name="track[ord]"></label><br>

	<label>Bonus Track?
		<select name="track[bonus]">
			<option value="true">Bonus</option>
			<option value="false">Regular</option>
		</select>
	<label><br>

	<input type="submit" value="Create a Track">
</form>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>

<ul>
	<li><%= @track.ord %></li>
	<li><%= @track.bonus ? 'Bonus Track' : 'Regular Track' %></li>
	<li><%= @track.lyrics %></li>
</ul>

<h3>Album</h3>
<ul>
	<li><%= link_to @track.album.name, album_url(@track.album) %></li>
</ul>

<h3>Band</h3>
<ul>
	<li><%= link_to @track.band.name, band_url(@track.band) %></li>
</ul>

<h3>Notes</h3>
<ul>
	<% @track.notes.each do |note| %>
		<li><%= note.body %>
			<%= button_to "Delete", note_url(note), method: "delete" %>
		</li>
	<% end %>
</ul>

<h3>Create a New Note</h3>

<form action="<%= track_notes_url(@track.id) %>" method="POST">
	<input type="hidden" 
	name="authenticity_token" 
	value="<%= form_authenticity_token%>">
	
	<input type="hidden" 
	name="note[track_id]" 
	value="<%= @track.id %>">
	
	<input type="hidden" 
	name="note[user_id]" 
	value="<%= @user.id%>">

	<label>Body
		<input type="text" name="note[body]">
	</label>

	<input type="submit" value="Create New Note">

</form>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if flash.now[:errors] %>
	<% flash.now[:errors].each do |error| %>
		<p><%= error %></p>
	<% end %>
<% end %>

<form action="<%= users_url %>" method="POST">
	<input type="hidden"
	name="authenticity_token"
	value="<%= form_authenticity_token%>">

	<label>Email
		<input type="text" name="user[email]">
	</label>

	<label>Password
		<input type="password" name="user[password]">
	</label>

	<input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1>User <%= @user.id %></h1>

<p><%= @user.email %></p>